# Generated by Django 5.2.6 on 2025-10-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='qr_code_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='ticket_sent_at',
            field=models.DateTimeField(blank=True, help_text='When e-ticket was emailed', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='qr_code_data',
            field=models.TextField(blank=True, help_text='QR code data for verification'),
        ),
    ]
