# Generated by Django 5.2.6 on 2025-10-15 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_qr_code_generated_at_booking_ticket_sent_at_and_more'),
        ('transport', '0004_trip_seat_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='selected_seats',
            field=models.JSONField(blank=True, default=list, help_text="List of selected seat numbers ['1A', '1B', '2C']"),
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(help_text='Ex: 1A, 1B, 2C, 2D', max_length=5)),
                ('row', models.IntegerField(help_text='Numéro de rangée (commence à 1)')),
                ('position', models.CharField(choices=[('left_window', 'Fenêtre gauche'), ('left_middle', 'Milieu gauche'), ('left_aisle', 'Couloir gauche'), ('right_aisle', 'Couloir droit'), ('right_window', 'Fenêtre droite')], max_length=20)),
                ('is_available', models.BooleanField(default=True, help_text='Siège disponible pour réservation')),
                ('passenger_name', models.CharField(blank=True, max_length=255, null=True)),
                ('reserved_until', models.DateTimeField(blank=True, help_text='Expiration de la réservation temporaire', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_seats', to='bookings.booking')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='transport.trip')),
            ],
            options={
                'ordering': ['row', 'position'],
                'indexes': [models.Index(fields=['trip', 'is_available'], name='bookings_se_trip_id_e4c4fc_idx')],
                'unique_together': {('trip', 'seat_number')},
            },
        ),
    ]
