# Generated by Django 5.2.6 on 2025-09-29 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_created_at_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='buscompany',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Associated bus company for company users', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.buscompany'),
        ),
        migrations.AlterField(
            model_name='buscompany',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
