# Generated by Django 5.2.6 on 2025-09-29 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_buscompany_verification_status_user_company_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='buscompany',
            table='accounts_buscompany',
        ),
    ]
