# Generated by Django 5.2.6 on 2025-09-29 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_buscompany_table'),
    ]

    operations = [
    ]
