# Generated by Django 5.2.6 on 2025-09-26 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name_plural': 'Cities'},
        ),
        migrations.AddField(
            model_name='city',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.CharField(default="Côte d'Ivoire", help_text='Country name', max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this city is available for new routes'),
        ),
        migrations.AlterField(
            model_name='city',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Latitude coordinate', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AlterField(
            model_name='city',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Longitude coordinate', max_digits=11, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(db_index=True, help_text="City name in French (e.g., 'Abidjan', 'Bouaké')", max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='state_province',
            field=models.CharField(blank=True, help_text="Region/Province (e.g., 'Lagunes', 'Vallée du Bandama')", max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='timezone',
            field=models.CharField(default='Africa/Abidjan', help_text='Timezone identifier', max_length=50),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['name', 'is_active'], name='locations_c_name_1ed397_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['country', 'is_active'], name='locations_c_country_1e395d_idx'),
        ),
    ]
