# Generated by Django 5.2.6 on 2025-10-08 12:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20250929_1637'),
        ('locations', '0002_alter_city_options_city_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Station name (e.g., 'Gare d'Adjamé')", max_length=200)),
                ('address', models.TextField(help_text='Full address of the station')),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number for this station', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, help_text='GPS latitude', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, help_text='GPS longitude', max_digits=11, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this station is currently operational')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(help_text='City where this station is located', on_delete=django.db.models.deletion.PROTECT, related_name='bus_stations', to='locations.city')),
                ('company', models.ForeignKey(help_text='Company that owns/operates this station', on_delete=django.db.models.deletion.CASCADE, related_name='bus_stations', to='accounts.buscompany')),
            ],
            options={
                'verbose_name': 'Bus Station',
                'verbose_name_plural': 'Bus Stations',
                'ordering': ['city__name', 'name'],
                'indexes': [models.Index(fields=['company', 'city'], name='locations_b_company_1cf445_idx'), models.Index(fields=['is_active'], name='locations_b_is_acti_9f2d14_idx'), models.Index(fields=['city', 'is_active'], name='locations_b_city_id_877948_idx')],
                'unique_together': {('company', 'city', 'name')},
            },
        ),
    ]
