# Generated by Django 5.2.6 on 2025-11-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_payment_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('stripe_card', 'Stripe Card'), ('wave', 'Wave Mobile Money'), ('orange_money', 'Orange Money'), ('mtn_money', 'MTN Mobile Money'), ('cash', 'Cash')], default='stripe_card', max_length=20),
        ),
    ]
