# Generated by Django 5.2.6 on 2025-09-22 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_duration_minutes', models.PositiveIntegerField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.buscompany')),
                ('destination_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_routes', to='locations.city')),
                ('origin_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_routes', to='locations.city')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('total_seats', models.PositiveIntegerField(default=50)),
                ('available_seats', models.PositiveIntegerField(default=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bus_number', models.CharField(blank=True, max_length=50)),
                ('bus_type', models.CharField(default='Standard', max_length=50)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('in_progress', 'In Progress'), ('delayed', 'Delayed'), ('on_time', 'On Time'), ('early', 'Early'), ('late', 'Late')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.route')),
            ],
        ),
    ]
