# Generated by Django 5.2.6 on 2025-09-26 11:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_created_at_alter_user_phone'),
        ('locations', '0002_alter_city_options_city_updated_at_and_more'),
        ('transport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['origin_city__name', 'destination_city__name']},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-departure_date', '-departure_time']},
        ),
        migrations.AddField(
            model_name='route',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this trip', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text='Base price in CFA francs', max_digits=10, validators=[django.core.validators.MinValueValidator(500), django.core.validators.MaxValueValidator(50000)]),
        ),
        migrations.AlterField(
            model_name='route',
            name='bus_company',
            field=models.ForeignKey(help_text='Company that operates this route', on_delete=django.db.models.deletion.CASCADE, related_name='company_routes', to='accounts.buscompany'),
        ),
        migrations.AlterField(
            model_name='route',
            name='destination_city',
            field=models.ForeignKey(help_text='Ending city', on_delete=django.db.models.deletion.CASCADE, related_name='destination_routes', to='locations.city'),
        ),
        migrations.AlterField(
            model_name='route',
            name='distance_km',
            field=models.PositiveIntegerField(blank=True, help_text='Distance in kilometers', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='route',
            name='estimated_duration_minutes',
            field=models.PositiveIntegerField(help_text='Estimated travel time in minutes', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(1440)]),
        ),
        migrations.AlterField(
            model_name='route',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this route is available for new trips'),
        ),
        migrations.AlterField(
            model_name='route',
            name='origin_city',
            field=models.ForeignKey(help_text='Starting city', on_delete=django.db.models.deletion.CASCADE, related_name='origin_routes', to='locations.city'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='arrival_time',
            field=models.TimeField(help_text='Expected arrival time'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='available_seats',
            field=models.PositiveIntegerField(default=50, help_text='Number of available seats', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='trip',
            name='bus_number',
            field=models.CharField(blank=True, help_text='Bus identification number', max_length=50),
        ),
        migrations.AlterField(
            model_name='trip',
            name='bus_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('vip', 'VIP'), ('luxury', 'Luxury'), ('express', 'Express'), ('sleeper', 'Sleeper')], default='standard', help_text='Type of bus service', max_length=20),
        ),
        migrations.AlterField(
            model_name='trip',
            name='departure_date',
            field=models.DateField(db_index=True, help_text='Date of departure'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='departure_time',
            field=models.TimeField(help_text='Time of departure'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Trip price in CFA francs', max_digits=10, validators=[django.core.validators.MinValueValidator(500), django.core.validators.MaxValueValidator(50000)]),
        ),
        migrations.AlterField(
            model_name='trip',
            name='route',
            field=models.ForeignKey(help_text='Route for this trip', on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='transport.route'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('in_progress', 'In Progress'), ('delayed', 'Delayed'), ('on_time', 'On Time'), ('early', 'Early'), ('late', 'Late')], db_index=True, default='draft', help_text='Current status of the trip', max_length=20),
        ),
        migrations.AlterField(
            model_name='trip',
            name='total_seats',
            field=models.PositiveIntegerField(default=50, help_text='Total number of seats in the bus', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('bus_company', 'origin_city', 'destination_city')},
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['bus_company', 'is_active'], name='transport_r_bus_com_911983_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['origin_city', 'destination_city', 'is_active'], name='transport_r_origin__2424bc_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['is_active'], name='transport_r_is_acti_137c8e_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['route', 'departure_date', 'status'], name='transport_t_route_i_ee3430_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['departure_date', 'status'], name='transport_t_departu_648826_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['status'], name='transport_t_status_17a22f_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['departure_date'], name='transport_t_departu_0da338_idx'),
        ),
    ]
