# Generated by Django 5.2.6 on 2025-10-08 17:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20250929_1637'),
        ('locations', '0003_busstation'),
        ('transport', '0002_alter_route_options_alter_trip_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='arrival_station',
            field=models.ForeignKey(blank=True, help_text="Gare d'arrivée", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='arriving_trips', to='locations.busstation'),
        ),
        migrations.AddField(
            model_name='trip',
            name='departure_station',
            field=models.ForeignKey(blank=True, help_text='Gare de départ', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='departing_trips', to='locations.busstation'),
        ),
        migrations.AddField(
            model_name='trip',
            name='is_template_generated',
            field=models.BooleanField(db_index=True, default=False, help_text='Si ce trajet a été auto-généré depuis un modèle'),
        ),
        migrations.CreateModel(
            name='TripTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.TimeField(help_text='Heure de départ quotidienne (ex: 09:00:00)')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Durée du trajet en minutes (ex: 240 pour 4 heures)', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(1440)])),
                ('operates_on_days', models.JSONField(default=list, help_text='Liste des jours [1-7] où 1=Lundi, 7=Dimanche. Ex: [1,2,3,4,5] = Lun-Ven')),
                ('bus_type', models.CharField(choices=[('standard', 'Standard'), ('vip', 'VIP'), ('luxury', 'Luxury'), ('express', 'Express'), ('sleeper', 'Sleeper')], default='standard', help_text='Type de bus pour cet horaire', max_length=20)),
                ('bus_number', models.CharField(help_text="Numéro d'identification du bus (ex: 'AB-001')", max_length=50)),
                ('total_seats', models.PositiveIntegerField(default=50, help_text='Nombre total de places disponibles', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('price', models.DecimalField(decimal_places=2, help_text='Prix par place en FCFA', max_digits=10, validators=[django.core.validators.MinValueValidator(500), django.core.validators.MaxValueValidator(50000)])),
                ('valid_from', models.DateField(help_text='Date à partir de laquelle ce modèle commence à générer des trajets')),
                ('valid_until', models.DateField(blank=True, help_text='Date de fin optionnelle pour ce modèle', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Si ce modèle génère actuellement des trajets')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arrival_station', models.ForeignKey(help_text="Gare d'arrivée", on_delete=django.db.models.deletion.PROTECT, related_name='arrival_templates', to='locations.busstation')),
                ('bus_company', models.ForeignKey(help_text='Compagnie qui opère cet horaire récurrent', on_delete=django.db.models.deletion.CASCADE, related_name='trip_templates', to='accounts.buscompany')),
                ('departure_station', models.ForeignKey(help_text='Gare de départ', on_delete=django.db.models.deletion.PROTECT, related_name='departure_templates', to='locations.busstation')),
            ],
            options={
                'verbose_name': 'Modèle de Trajet',
                'verbose_name_plural': 'Modèles de Trajets',
                'ordering': ['departure_station__city__name', 'departure_time'],
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Modèle qui a généré ce trajet (si auto-généré)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_trips', to='transport.triptemplate'),
        ),
        migrations.AddIndex(
            model_name='triptemplate',
            index=models.Index(fields=['bus_company', 'is_active'], name='transport_t_bus_com_35755e_idx'),
        ),
        migrations.AddIndex(
            model_name='triptemplate',
            index=models.Index(fields=['departure_station', 'arrival_station'], name='transport_t_departu_aae42d_idx'),
        ),
        migrations.AddIndex(
            model_name='triptemplate',
            index=models.Index(fields=['valid_from', 'valid_until'], name='transport_t_valid_f_932838_idx'),
        ),
        migrations.AddIndex(
            model_name='triptemplate',
            index=models.Index(fields=['is_active'], name='transport_t_is_acti_706cb4_idx'),
        ),
    ]
