# Generated by Django 5.2.6 on 2025-10-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_trip_arrival_station_trip_departure_station_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='seat_layout',
            field=models.CharField(choices=[('3x2', 'Standard (3+2)'), ('2x2', 'VIP/Luxury (2+2)')], default='3x2', help_text='Configuration des sièges du bus', max_length=10),
        ),
    ]
